---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.3
  - name: ubuntu-16.04

suites:
  - name: hypervisors
    run_list:
    - recipe[gns3::hypervisors]
    attributes: { gns3: { hypervisors: array('kvm') } }
